menu:
  Home: /
  Archives: /archives
  About: /about
 
widgets:
- search
- category
- tag
- weibo
- externlink
- 163music

recent_posts: 最近更新
excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true

google_analytics:
baidu_analytics: true
rss: /atom.xml

comment_provider: 
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
